/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import prueba.Boton;
import prueba.Funciones;
import prueba.Índice;

/**
 *
 * @author HP15DA0023LA
 */
public class Interfaz extends javax.swing.JFrame implements ActionListener {

    ArrayList<Boton> lista;
    Funciones Fun;
    RandomAccessFile Biblioteca;
    String rutaBiblioteca;
    ArrayList<Índice> inAutor;
    ArrayList<Índice> inPista;
    ArrayList<Índice> inAño;
            
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        VerificarBiblio();
        Fun= new Funciones();
        lista = new ArrayList();
        
    }
    public void actionPerformed(ActionEvent e)
    {
        Boton temp2= (Boton)e.getSource();
        VentanaInfo ven= new VentanaInfo();
        ven.agregar(temp2);
        ven.toFront();
        ven.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BAbrir = new javax.swing.JButton();
        BotonArtista = new javax.swing.JButton();
        BotonAlbum = new javax.swing.JButton();
        BotonPista = new javax.swing.JButton();
        BtnVaciarPantalla = new javax.swing.JButton();
        AgregarRuta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Panel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        BuscarArtista = new javax.swing.JButton();
        BuscarPista = new javax.swing.JButton();
        BuscarAño = new javax.swing.JButton();
        Texto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        BAbrir.setText("Abrir archivo");
        BAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAbrirActionPerformed(evt);
            }
        });

        BotonArtista.setText("Artistas");
        BotonArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonArtistaActionPerformed(evt);
            }
        });

        BotonAlbum.setText("Album");
        BotonAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAlbumActionPerformed(evt);
            }
        });

        BotonPista.setText("Pista");
        BotonPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPistaActionPerformed(evt);
            }
        });

        BtnVaciarPantalla.setText("Vaciar Pantalla");
        BtnVaciarPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVaciarPantallaActionPerformed(evt);
            }
        });

        AgregarRuta.setText("Agregar Ruta");
        AgregarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarRutaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BotonAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnVaciarPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonPista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AgregarRuta, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BAbrir)
                    .addComponent(AgregarRuta)
                    .addComponent(BtnVaciarPantalla))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonArtista)
                    .addComponent(BotonAlbum)
                    .addComponent(BotonPista))
                .addGap(30, 30, 30))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(51, 255, 204));
        jPanel3.setForeground(new java.awt.Color(0, 204, 204));

        BuscarArtista.setText("Buscar Artista");
        BuscarArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarArtistaActionPerformed(evt);
            }
        });

        BuscarPista.setText("Buscar Pista");
        BuscarPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPistaActionPerformed(evt);
            }
        });

        BuscarAño.setText("Buscar Año");
        BuscarAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarAñoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Texto)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(BuscarArtista)
                        .addGap(18, 18, 18)
                        .addComponent(BuscarPista, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(BuscarAño, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(Texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarArtista)
                    .addComponent(BuscarPista)
                    .addComponent(BuscarAño))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAbrirActionPerformed
        JFileChooser selector= new JFileChooser();
        selector.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int opcion= selector.showOpenDialog(this);
        if(opcion==JFileChooser.APPROVE_OPTION)
            {
                File fichero= selector.getSelectedFile();
                getFiles(fichero.getAbsolutePath()); // tengo un metodo llamado getFiles ahí abajo
                
            }       
    }//GEN-LAST:event_BAbrirActionPerformed

    private void BotonArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonArtistaActionPerformed
        VaciarLista();
        LlenarLista();
        MostrarArtista();
    }//GEN-LAST:event_BotonArtistaActionPerformed

    private void BotonAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAlbumActionPerformed
        VaciarLista();
        LlenarLista();
        MostrarAlbum();
    }//GEN-LAST:event_BotonAlbumActionPerformed

    private void BotonPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPistaActionPerformed
        VaciarLista();
        LlenarLista();
        MostrarPista();
    }//GEN-LAST:event_BotonPistaActionPerformed

    private void BtnVaciarPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVaciarPantallaActionPerformed
        this.Panel.removeAll();
    }//GEN-LAST:event_BtnVaciarPantallaActionPerformed

    private void AgregarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarRutaActionPerformed
        JFileChooser selector= new JFileChooser();
        selector.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int opcion= selector.showOpenDialog(this);
        if(opcion==JFileChooser.APPROVE_OPTION)
            {
            try {
                File fichero= selector.getSelectedFile();
             
                rutaBiblioteca= fichero.getAbsolutePath()+"\\BibliotecaMusical.musicB";
                RandomAccessFile bibli= new RandomAccessFile(rutaBiblioteca,"rw"); //puede que aquí sea buena idea para agregar el separador y los punteros así como indices
                bibli.writeBytes("BAC");
                bibli.writeInt(19);//posicion del primer indice artista
                bibli.writeInt(21);//posicion del segundo indice pista
                bibli.writeInt(23);//posicion del tercer indice año
                bibli.writeBytes("MERC");
                bibli.writeShort(0);//el tamaño del primer indice
                bibli.writeShort(0); //el tamaño del segundo indice
                bibli.writeShort(0);// el tamaño del tercer indice
                bibli.close();
                RandomAccessFile revision = new RandomAccessFile("Direccion.path","rw");
                revision.writeByte(1);
                revision.writeBytes(rutaBiblioteca);
                revision.close();
                BotonArtista.setEnabled(true);
                BAbrir.setEnabled(true);
                BotonAlbum.setEnabled(true);
                BotonPista.setEnabled(true);
                BtnVaciarPantalla.setEnabled(true);
                AgregarRuta.setEnabled(false);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
                       
            }       
    }//GEN-LAST:event_AgregarRutaActionPerformed

    private void BuscarArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarArtistaActionPerformed
        String artista= Texto.getText();
        if(!"".equals(artista))
        {
               
                try {
                Biblioteca=new RandomAccessFile(rutaBiblioteca,"rw");
                Biblioteca.seek(3);
                int posicionPuntero= Biblioteca.readInt();
                Biblioteca.seek(posicionPuntero);
                short cantidadEnIndice= Biblioteca.readShort();
                int verdaderoPuntero=0;
                byte[] nuevoArtista = new byte[artista.length()];
                
                for(int i=0; i<artista.length(); i++)
                {
                    nuevoArtista[i] = (byte) artista.charAt(i);
                }
                artista= new String(nuevoArtista); 
                int contador=0;
                for(int i=0; i<cantidadEnIndice; i++)
                {
                    int tamañoDescripcion= Biblioteca.readShort()-1; //leo el short con el tamaño del nombre
                    
                    Biblioteca.readByte();
                    byte[] descripcion = new byte[tamañoDescripcion];
                    Biblioteca.read(descripcion); //le asigno el nombre (básicamente ya lo tengo) 
                    String descripString=new String(descripcion); 
                    int puntero= Biblioteca.readInt(); //obtengo el puntero asignado a ese nombre
                    
                    if(artista.equals(descripString)&&contador==0){
                        verdaderoPuntero= puntero;
                        contador=1;
                        
                    }
                    
                }
                if(verdaderoPuntero!=0)
                {
                    Biblioteca.seek(verdaderoPuntero);
                    byte[] lectorT = new byte[4];
                    Biblioteca.read(lectorT);
                    String identificador= new String(lectorT);
                   
                    Boton b = new Boton();
                    if("BEBP".equals(identificador))
                    {
                        lectorT = new byte[4];
                        Biblioteca.read(lectorT);
                        identificador= new String(lectorT);
                        
                    }
                    while((!"BEBP".equals(identificador))&&(!"MERC".equals(identificador)))
                    {   
                        
                        short tamaño= Biblioteca.readShort();
                        byte[] info = new byte[tamaño];
                        Biblioteca.read(info);
                        b.DiferenciadorTags(identificador, info);
                        //
                        lectorT = new byte[4];
                        Biblioteca.read(lectorT);
                        identificador= new String(lectorT); 
                        
                        
                    }
                    this.Panel.removeAll();
                    this.Panel.setLayout(new java.awt.GridLayout(1, 1));
                    b.addActionListener(this);
                    b.setText(b.getArtista());
                    b.setVisible(true);
                    this.Panel.add(b);
                }
                Biblioteca.close();
                Texto.setText("");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }//GEN-LAST:event_BuscarArtistaActionPerformed

    private void BuscarPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPistaActionPerformed
       String pista= Texto.getText();
       if(!"".equals(pista))
        {
                try {
                Biblioteca=new RandomAccessFile(rutaBiblioteca,"rw");
                Biblioteca.seek(7);
                int posicionPuntero= Biblioteca.readInt();
                Biblioteca.seek(posicionPuntero);
                short cantidadEnIndice= Biblioteca.readShort();
                
                int verdaderoPuntero=0;
                byte[] nuevoArtista = new byte[pista.length()];
                
                for(int i=0; i<pista.length(); i++)
                {
                    nuevoArtista[i] = (byte) pista.charAt(i);
                }
                pista= new String(nuevoArtista); 
                int contador=0;
                for(int i=0; i<cantidadEnIndice; i++)
                {
                    int tamañoDescripcion= Biblioteca.readShort()-1; //leo el short con el tamaño del nombre
                    
                    Biblioteca.readByte();
                    byte[] descripcion = new byte[tamañoDescripcion];
                    Biblioteca.read(descripcion); //le asigno el nombre (básicamente ya lo tengo) 
                    String descripString=new String(descripcion); 
                    int puntero= Biblioteca.readInt(); //obtengo el puntero asignado a ese nombre
                    
                    if(pista.equals(descripString)&&contador==0){
                        verdaderoPuntero= puntero;
                        contador=1;
                       
                    }
                    
                }
                if(verdaderoPuntero!=0)
                {
                    Biblioteca.seek(verdaderoPuntero);
                    byte[] lectorT = new byte[4];
                    Biblioteca.read(lectorT);
                    String identificador= new String(lectorT);
                    
                    Boton b = new Boton();
                    if("BEBP".equals(identificador))
                    {
                        lectorT = new byte[4];
                        Biblioteca.read(lectorT);
                        identificador= new String(lectorT);
                        
                    }
                    while((!"BEBP".equals(identificador))&&(!"MERC".equals(identificador)))
                    {   
                        
                        short tamaño= Biblioteca.readShort();
                        byte[] info = new byte[tamaño];
                        Biblioteca.read(info);
                        b.DiferenciadorTags(identificador, info);
                        //
                        lectorT = new byte[4];
                        Biblioteca.read(lectorT);
                        identificador= new String(lectorT); 
                        
                        
                    }
                    this.Panel.removeAll();
                    this.Panel.setLayout(new java.awt.GridLayout(1, 1));
                    b.addActionListener(this);
                    b.setText(b.getPista());
                    b.setVisible(true);
                    this.Panel.add(b);
                }
                Biblioteca.close();
                Texto.setText("");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_BuscarPistaActionPerformed

    private void BuscarAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarAñoActionPerformed
        String año= Texto.getText();
        if(!"".equals(año))
        {
                try {
                Biblioteca=new RandomAccessFile(rutaBiblioteca,"rw");
                Biblioteca.seek(11);
                int posicionPuntero= Biblioteca.readInt();
                Biblioteca.seek(posicionPuntero);
                System.out.println("posicion puntero: "+posicionPuntero);
                short cantidadEnIndice= Biblioteca.readShort();
                int verdaderoPuntero=0;
                byte[] nuevoArtista = new byte[año.length()];
                
                for(int i=0; i<año.length(); i++)
                {
                    nuevoArtista[i] = (byte) año.charAt(i);
                }
                año= new String(nuevoArtista); 
                int contador=0;
                for(int i=0; i<cantidadEnIndice; i++)
                {
                    int tamañoDescripcion= Biblioteca.readShort()-1; //leo el short con el tamaño del nombre
                    
                    Biblioteca.readByte();
                    byte[] descripcion = new byte[tamañoDescripcion];
                    Biblioteca.read(descripcion); //le asigno el nombre (básicamente ya lo tengo) 
                    String descripString=new String(descripcion); 
                    int puntero= Biblioteca.readInt(); //obtengo el puntero asignado a ese nombre
                    
                    if(año.equals(descripString)&&contador==0){
                        verdaderoPuntero= puntero;
                        contador=1;
                        
                    }
                    
                }
                if(verdaderoPuntero!=0)
                {
                    Biblioteca.seek(verdaderoPuntero);
                    byte[] lectorT = new byte[4];
                    Biblioteca.read(lectorT);
                    String identificador= new String(lectorT);
                    
                    Boton b = new Boton();
                    if("BEBP".equals(identificador))
                    {
                        lectorT = new byte[4];
                        Biblioteca.read(lectorT);
                        identificador= new String(lectorT);
                        
                    }
                    while((!"BEBP".equals(identificador))&&(!"MERC".equals(identificador)))
                    {   
                        
                        short tamaño= Biblioteca.readShort();
                        byte[] info = new byte[tamaño];
                        Biblioteca.read(info);
                        b.DiferenciadorTags(identificador, info);
                        //
                        lectorT = new byte[4];
                        Biblioteca.read(lectorT);
                        identificador= new String(lectorT); 
                        
                        
                    }
                    this.Panel.removeAll();
                    this.Panel.setLayout(new java.awt.GridLayout(1, 1));
                    b.addActionListener(this);
                    b.setText(b.getAño());
                    b.setVisible(true);
                    this.Panel.add(b);
                }
                Biblioteca.close();
                Texto.setText("");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_BuscarAñoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    public void VaciarLista()
    {
        lista=new ArrayList();
        this.Panel.removeAll();
    }
    public void LlenarLista()
    {
        lista=new ArrayList();
        try {
            Biblioteca=new RandomAccessFile(rutaBiblioteca,"rw");
            Biblioteca.seek(15);
            byte[] lectorT = new byte[4];
            Biblioteca.read(lectorT);
            String identificador= new String(lectorT);
            Boton b = new Boton();
            long tam = Biblioteca.length();
            if(tam!=0)
            {
                while(!"MERC".equals(identificador))
                {
                    if("BEBP".equals(identificador))
                    {
                        lectorT = new byte[4];
                        Biblioteca.read(lectorT);
                        identificador= new String(lectorT);
                    }
                    short tamaño= Biblioteca.readShort();
                    byte[] info = new byte[tamaño];
                    Biblioteca.read(info);
                    b.DiferenciadorTags(identificador, info);
                    //
                    lectorT = new byte[4];
                    Biblioteca.read(lectorT);
                    identificador= new String(lectorT);
                    if(("BEBP".equals(identificador))||("MERC".equals(identificador)))
                    {
                        lista.add(b);
                        b= new Boton();
                    }
                }
            }
            Biblioteca.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void MostrarArtista()
    {
        this.Panel.removeAll();
        this.Panel.setLayout(new java.awt.GridLayout(lista.size(), 1));
        for(int i=0; i<lista.size();i++)
        {
            Boton b= new Boton();
            b= lista.get(i);
            b.addActionListener(this);
            b.setText(b.getArtista());
            b.setVisible(true);
            this.Panel.add(b);
        }
    }
    public void MostrarAlbum()
    {
        this.Panel.removeAll();
        this.Panel.setLayout(new java.awt.GridLayout(lista.size(), 1));
        for(int i=0; i<lista.size();i++)
        {
            Boton bAlbum= new Boton();
            bAlbum= lista.get(i);
            bAlbum.addActionListener(this);
            bAlbum.setText(bAlbum.getAlbum());
            bAlbum.setVisible(true);
            this.Panel.add(bAlbum);
        }
    }
    public void MostrarPista()
    {
        this.Panel.removeAll();
        this.Panel.setLayout(new java.awt.GridLayout(lista.size(), 1));
        for(int i=0; i<lista.size();i++)
        {
            Boton bPista= new Boton();
            bPista= lista.get(i);
            bPista.addActionListener(this);
            bPista.setText(bPista.getPista());
            bPista.setVisible(true);
            this.Panel.add(bPista);
        }
    }
    public void getFiles( String dir_path ) {

            String[] arr_res = null;
           
            File f = new File( dir_path );
            Funciones fun= new Funciones();

            if ( f.isDirectory( )) {

                List<String> res   = new ArrayList<>();
                File[] arr_content = f.listFiles();
                String[] lista= f.list();
                f.getPath();
                int size = lista.length;

                for ( int i = 0; i < size; i ++ ) {
                    
                    String nuevaRuta = dir_path+"\\"+lista[i];
                    File fNuevo = new File(nuevaRuta);
                    if(fNuevo.isDirectory())
                    {
                        getFiles(nuevaRuta);
                    }
                    if(fNuevo.isFile())
                    {
                        if(fun.esMp3(nuevaRuta))
                        {
                            agregarCancion(nuevaRuta);
                        }
                    }
                }

                arr_res = lista;

            } else
                System.err.println( "¡ Path NO válido !" );

        }
    
    public void agregarCancion(String ruta)
    {
        inAutor = new ArrayList();
        inPista = new ArrayList();
        inAño = new ArrayList();
        int c1=0, c2=0,c3=0;
        try {
            Biblioteca=new RandomAccessFile(rutaBiblioteca,"rw");
            //debería leer si tiene la cabecera, obtener la dirección de los indices y los indices
            byte[] cabecera = new byte[3];
            Biblioteca.read(cabecera);
            String tagCab=new String(cabecera);
            if("BAC".equals(tagCab))
            {
                int posicionPrimerIndice=Biblioteca.readInt();
                Biblioteca.seek(posicionPrimerIndice);
//              TextoBooleano.setText("si es"); //esto no sé si vale la pena dejarlo o no
                //tengo que mandar la info a los punteros
                short cantPunteros= Biblioteca.readShort();
                while(cantPunteros!=0)
                {
                    Índice ind= new Índice();
                    //ind.setTamañoDef(Biblioteca.readShort());
                    ind.setTamañoDef((int) Biblioteca.readShort()); //el tamaño 
                    byte[] definicion = new byte[ind.getTamañoDef()];
                    Biblioteca.read(definicion);
                    String nDefi=new String(definicion); 
                    ind.setDefinicion(nDefi); //la definición
                    ind.setPuntero(Biblioteca.readInt()); //el puntero
                    inAutor.add(ind);
                    cantPunteros--;
                }
                cantPunteros= Biblioteca.readShort();
                while(cantPunteros!=0)
                {
                    Índice ind= new Índice();
                    //ind.setTamañoDef(Biblioteca.readShort());
                    ind.setTamañoDef((int) Biblioteca.readShort()); //el tamaño 
                    byte[] definicion = new byte[ind.getTamañoDef()];
                    Biblioteca.read(definicion);
                    String nDefi=new String(definicion); 
                    ind.setDefinicion(nDefi); //la definición
                    ind.setPuntero(Biblioteca.readInt()); //el puntero
                    inPista.add(ind);
                    cantPunteros--;
                }
                cantPunteros= Biblioteca.readShort();
                while(cantPunteros!=0)
                {
                    Índice ind= new Índice();
                    //ind.setTamañoDef(Biblioteca.readShort());
                    ind.setTamañoDef((int) Biblioteca.readShort()); //el tamaño 
                    byte[] definicion = new byte[ind.getTamañoDef()];
                    Biblioteca.read(definicion);
                    String nDefi=new String(definicion); 
                    ind.setDefinicion(nDefi); //la definición
                    ind.setPuntero(Biblioteca.readInt()); //el puntero
                    inAño.add(ind);
                    cantPunteros--;
                }
                Biblioteca.seek(posicionPrimerIndice-4); //el menos 4 es por el MERC que había agregado antes
                int posActX= (int) Biblioteca.getFilePointer();
                Biblioteca.writeBytes("BEBP"); //este es mi separador
                Biblioteca.writeBytes("PATH");
                Biblioteca.writeShort(ruta.length());
                Biblioteca.writeBytes(ruta);
                try {
                            RandomAccessFile archivo= new RandomAccessFile(ruta,"rw");
                            for(int i=1; i<=10;i++)
                            {
                                archivo.readByte();
                            }
                            byte[] tagB = new byte[4];
                            archivo.read(tagB);
                            String tagN=new String(tagB);

                            short posic=Fun.ObtenerTag(tagN);
                            while(posic!=-3)
                            {

                                int tamaño =  archivo.readInt();
                                for(int i=0; i<2;i++)
                                {
                                    archivo.readByte();
                                }
                                byte[] contenido = new byte[tamaño];
                                archivo.read(contenido);
                                String tCon= new String(contenido);

                                if(posic!=-1)
                                {
                                    if(tagN.equals("TPE1")) //para agregar a indice artista
                                    {
                                        Índice index= new Índice();
                                        index.setPuntero(posActX);
                                        index.setDefinicion(tCon);
                                        index.setTamañoDef(tCon.length());
                                        inAutor.add(index);
                                    }
                                    else if(tagN.equals("TDRC"))//para agregar a indice año
                                    {
                                        Índice index= new Índice();
                                        index.setPuntero(posActX);
                                        index.setDefinicion(tCon);
                                        index.setTamañoDef(tCon.length());
                                        inAño.add(index);
                                    }
                                    else if(tagN.equals("TIT2"))//para agregar a indice pista
                                    {
                                        Índice index= new Índice();
                                        index.setPuntero(posActX);
                                        index.setDefinicion(tCon);
                                        index.setTamañoDef(tCon.length());
                                        inPista.add(index);
                                    }
                                    Biblioteca.writeBytes(tagN); //escribo la cabecera del tag
                                    //esto de aquí es para almacenar los tags en 
                                    Biblioteca.writeShort(tCon.length());
                                    Biblioteca.writeBytes(tCon);
                                    //
    //                                TextR.setText(TextR.getText()+Fun.TraducirTag(posic)+": " + tCon+"-"); //esto ya no me sirve
                                }
                                tagB = new byte[4];
                                archivo.read(tagB);
                                tagN=new String(tagB);
                                posic=Fun.ObtenerTag(tagN);
                            }
                            archivo.close();
                        } catch (FileNotFoundException ex) {
                            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
                        }
                Biblioteca.writeBytes("MERC"); //esto indica que es el final
                //luego de agregar una canción antes de cerrarla debería colocar nuevamente los indices, pero actualizados, y actualizar los punteros
                //aquí debo de volver a colocar los indices
                
                //aquí tengo que actualizar el puntero
                int posicionActual= (int) Biblioteca.getFilePointer();
                Biblioteca.writeShort(inAutor.size());
                Biblioteca.seek(3);
                Biblioteca.writeInt(posicionActual);
                Biblioteca.seek(posicionActual+2);
                for(int i=0;i<inAutor.size();i++)
                {
                    Índice auxI = new Índice();
                    auxI= inAutor.get(i);
                    
                    if(!"".equals(auxI.getDefinicion()))
                    {
                        Biblioteca.writeShort(auxI.getTamañoDef());
                        Biblioteca.writeBytes(auxI.getDefinicion());
                        Biblioteca.writeInt(auxI.getPuntero());
                    }
                }
                posicionActual= (int) Biblioteca.getFilePointer();
                
                Biblioteca.writeShort(inPista.size());
                Biblioteca.seek(7);
                Biblioteca.writeInt(posicionActual);
                Biblioteca.seek(posicionActual+2);
                for(int i=0;i<inPista.size();i++)
                {
                    Índice auxI = new Índice();
                    auxI= inPista.get(i);
                    
                    if(!"".equals(auxI.getDefinicion()))
                    {
                        Biblioteca.writeShort(auxI.getTamañoDef());
                        Biblioteca.writeBytes(auxI.getDefinicion());
                        Biblioteca.writeInt(auxI.getPuntero());
                    }
                   
                }
                posicionActual= (int) Biblioteca.getFilePointer();
                Biblioteca.writeShort(inAño.size());
                Biblioteca.seek(11);
                Biblioteca.writeInt(posicionActual);
                Biblioteca.seek(posicionActual+2);
                for(int i=0;i<inAño.size();i++)
                {
                    Índice auxI = new Índice();
                    auxI= inAño.get(i);
                    
                    if(!"".equals(auxI.getDefinicion()))
                    {
                        Biblioteca.writeShort(auxI.getTamañoDef());
                        Biblioteca.writeBytes(auxI.getDefinicion());
                        Biblioteca.writeInt(auxI.getPuntero());
                    }
                }
                Biblioteca.close();
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    private String VerificarBiblio()
    {
        try {
            RandomAccessFile revision = new RandomAccessFile("Direccion.path","rw");
            if(revision.length()==0)
            {
                BotonArtista.setEnabled(false);
                BAbrir.setEnabled(false);
                BotonAlbum.setEnabled(false);
                BotonPista.setEnabled(false);
                BtnVaciarPantalla.setEnabled(false);
            }
            else{
                AgregarRuta.setEnabled(false);
                revision.readByte();
                rutaBiblioteca= revision.readLine();
            }
            revision.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return rutaBiblioteca;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarRuta;
    private javax.swing.JButton BAbrir;
    private javax.swing.JButton BotonAlbum;
    private javax.swing.JButton BotonArtista;
    private javax.swing.JButton BotonPista;
    private javax.swing.JButton BtnVaciarPantalla;
    private javax.swing.JButton BuscarArtista;
    private javax.swing.JButton BuscarAño;
    private javax.swing.JButton BuscarPista;
    private javax.swing.JPanel Panel;
    private javax.swing.JTextField Texto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
